steps:
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build',
           '-t', '$_REGION-docker.pkg.dev/$PROJECT_ID/carona_app-$BRANCH_NAME/$BRANCH_NAME:$SHORT_SHA', '.']

  # Docker push to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push',  '$_REGION-docker.pkg.dev/$PROJECT_ID/carona_app-$BRANCH_NAME/$BRANCH_NAME:$SHORT_SHA']

  # Deploy to Cloud Run
  - name: 'google/cloud-sdk'
    args: ['gcloud', 'run', 'deploy', 'carona_app-$BRANCH_NAME',
           '--image=$_REGION-docker.pkg.dev/$PROJECT_ID/carona_app-$BRANCH_NAME/$BRANCH_NAME:$SHORT_SHA',
           '--region', '$_REGION', '--platform', 'managed',
           '--allow-unauthenticated']

  
  
options:
  dynamic_substitutions: true
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _INSTANCE_NAME: django-instance
  _REGION: us-central1
  _INSTANCE_CONNECTION_NAME: ${PROJECT_ID}:${_REGION}:${_INSTANCE_NAME}
